#pragma once
#include <F4SE/F4SE.h>
#include <RE/Fallout.h>
#include <REL/Relocation.h>
#include <spdlog/spdlog.h>
#include <Windows.h>
#include <algorithm>
#include <atomic>
#include <chrono>
#include <mutex>
#include <memory>
#include <cmath>
